-- 1A

SELECT lpad('-',2*(level-1),'|-') || t.owner||'.'||t.type_name||' (FINAL:'||t.final||', 
INSTANTIABLE:'||t.instantiable||', ATTRIBUTES:'||t.attributes||', METHODS:'||t.methods||')'
FROM all_types t
START WITH t.type_name = 'ST_GEOMETRY'
CONNECT BY PRIOR t.type_name = t.supertype_name
AND PRIOR t.owner = t.owner;

-- 1B

SELECT DISTINCT m.method_name
FROM all_type_methods m
WHERE m.type_name LIKE 'ST_POLYGON'
AND m.owner = 'MDSYS'
ORDER BY 1;

-- 1C

CREATE TABLE MYST_MAJOR_CITIES (
FIPS_CNTRY VARCHAR2(2),
CITY_NAME VARCHAR2(40),
STGEOM ST_POINT );

-- 1D

DESC MAJOR_CITIES;

INSERT INTO MYST_MAJOR_CITIES
SELECT MC.FIPS_CNTRY, MC.CITY_NAME, 
    TREAT(ST_POINT.FROM_SDO_GEOM(MC.GEOM) AS ST_POINT) STGEOM
FROM MAJOR_CITIES MC;

SELECT * FROM MYST_MAJOR_CITIES;

-- 2A

INSERT INTO MYST_MAJOR_CITIES
VALUES('PL', 'Szczyrk', ST_POINT(19.036107, 49.718655, 8307));

-- 3A

CREATE TABLE MYST_COUNTRY_BOUNDARIES (
FIPS_CNTRY VARCHAR2(2),
CNTRY_NAME VARCHAR2(40),
STGEOM ST_MULTIPOLYGON );

-- 3B

DESC COUNTRY_BOUNDARIES;

INSERT INTO MYST_COUNTRY_BOUNDARIES
SELECT CB.FIPS_CNTRY, CB.CNTRY_NAME, ST_MULTIPOLYGON(CB.GEOM)
FROM COUNTRY_BOUNDARIES CB;

-- 3C

SELECT MCB.STGEOM.ST_GEOMETRYTYPE() AS TYP_OBIEKTU, 
    COUNT(MCB.STGEOM.ST_GEOMETRYTYPE())  AS ILE
FROM MYST_COUNTRY_BOUNDARIES MCB
GROUP BY MCB.STGEOM.ST_GEOMETRYTYPE();

-- 3D

SELECT MCB.STGEOM.ST_ISSIMPLE()
FROM MYST_COUNTRY_BOUNDARIES MCB;

-- 4A

SELECT MCB.CNTRY_NAME, COUNT(*)
FROM MYST_MAJOR_CITIES MMC, MYST_COUNTRY_BOUNDARIES MCB
WHERE MCB.STGEOM.ST_CONTAINS(MMC.STGEOM) = 1
GROUP BY MCB.CNTRY_NAME;

-- 4B

SELECT A.CNTRY_NAME AS A_NAME, B.CNTRY_NAME AS B_NAME
FROM MYST_COUNTRY_BOUNDARIES A, MYST_COUNTRY_BOUNDARIES B
WHERE B.CNTRY_NAME = 'Czech Republic' 
AND B.STGEOM.ST_TOUCHES(A.STGEOM) = 1;

-- 4C

SELECT * FROM RIVERS;

SELECT DISTINCT MCB.CNTRY_NAME, R.NAME
FROM RIVERS R, MYST_COUNTRY_BOUNDARIES MCB
WHERE MCB.CNTRY_NAME = 'Czech Republic' 
AND MCB.STGEOM.ST_CROSSES(ST_LINESTRING(R.GEOM)) = 1;

-- 4D

SELECT TREAT(A.STGEOM.ST_UNION(B.STGEOM) AS ST_POLYGON).ST_AREA() POWIERZCHNIA
FROM MYST_COUNTRY_BOUNDARIES A, MYST_COUNTRY_BOUNDARIES B
WHERE A.CNTRY_NAME = 'Czech Republic' 
AND B.CNTRY_NAME = 'Slovakia';

-- 4E

SELECT MCB.STGEOM.ST_DIFFERENCE(ST_GEOMETRY(WB.GEOM)) AS OBIEKT, MCB.STGEOM.ST_DIFFERENCE(ST_GEOMETRY(WB.GEOM)).ST_GEOMETRYTYPE() WEGRY_BEZ
FROM MYST_COUNTRY_BOUNDARIES MCB, WATER_BODIES WB
WHERE MCB.CNTRY_NAME = 'Hungary' 
AND WB.NAME = 'Balaton';

-- 5A

SELECT MCB.CNTRY_NAME, COUNT(*)
FROM MYST_MAJOR_CITIES MMC, MYST_COUNTRY_BOUNDARIES MCB
WHERE SDO_WITHIN_DISTANCE(MMC.STGEOM, MCB.STGEOM, 'distance=100 unit=km') = 'TRUE' 
AND MCB.CNTRY_NAME = 'Poland'
GROUP BY MCB.CNTRY_NAME;

EXPLAIN PLAN FOR
SELECT MCB.CNTRY_NAME, COUNT(*)
FROM MYST_MAJOR_CITIES MMC, MYST_COUNTRY_BOUNDARIES MCB
WHERE SDO_WITHIN_DISTANCE(MMC.STGEOM, MCB.STGEOM, 'distance=100 unit=km') = 'TRUE' 
AND MCB.CNTRY_NAME = 'Poland'
GROUP BY MCB.CNTRY_NAME;

SELECT plan_table_output 
FROM TABLE(dbms_xplan.display('plan_table', null, 'basic'));

-- 5B

INSERT INTO USER_SDO_GEOM_METADATA
SELECT 'MYST_MAJOR_CITIES', 'STGEOM', MD.DIMINFO, MD.SRID
FROM ALL_SDO_GEOM_METADATA MD
WHERE MD.TABLE_NAME = 'MAJOR_CITIES';

-- 5C

CREATE INDEX MMC_INDEX ON MYST_MAJOR_CITIES(STGEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- 5D

SELECT MCB.CNTRY_NAME, COUNT(*)
FROM MYST_MAJOR_CITIES MMC, MYST_COUNTRY_BOUNDARIES MCB
WHERE SDO_WITHIN_DISTANCE(MMC.STGEOM, MCB.STGEOM, 'distance=100 unit=km') = 'TRUE' 
AND MCB.CNTRY_NAME = 'Poland'
GROUP BY MCB.CNTRY_NAME;

EXPLAIN PLAN FOR
SELECT MCB.CNTRY_NAME, COUNT(*)
FROM MYST_MAJOR_CITIES MMC, MYST_COUNTRY_BOUNDARIES MCB
WHERE SDO_WITHIN_DISTANCE(MMC.STGEOM, MCB.STGEOM, 'distance=100 unit=km') = 'TRUE' 
AND MCB.CNTRY_NAME = 'Poland'
GROUP BY MCB.CNTRY_NAME;

SELECT plan_table_output 
FROM TABLE(dbms_xplan.display('plan_table', null, 'basic'));