-- 1A

CREATE TABLE A6_LRS (GEOM SDO_GEOMETRY);

-- 1B

INSERT INTO A6_LRS
SELECT SAR.GEOM
FROM STREETS_AND_RAILROADS SAR, MAJOR_CITIES MC
WHERE MC.CITY_NAME = 'Koszalin' 
AND SDO_RELATE(SAR.GEOM, SDO_GEOM.SDO_BUFFER(MC.GEOM, 10, 1, 'unit=km'), 'MASK=ANYINTERACT') = 'TRUE';

SELECT * FROM A6_LRS;

-- 1C

SELECT SDO_GEOM.SDO_LENGTH(GEOM, 1, 'unit=km') DISTANCE, ST_LINESTRING(GEOM).ST_NUMPOINTS() ST_NUMPOINTS
FROM A6_LRS;

-- 1D

UPDATE A6_LRS
SET GEOM = SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0, 276.681315);

-- 1E

INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('A6_LRS', 'GEOM', MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
    MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
    MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1) ), 8307);

-- 1F

CREATE INDEX A6_LRS_INDEX ON A6_LRS(GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- 2A

SELECT SDO_LRS.VALID_MEASURE(GEOM, 500) VALID_500
FROM A6_LRS;

-- 2B

SELECT SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) END_PT
FROM A6_LRS;

-- 2C

SELECT SDO_LRS.LOCATE_PT(GEOM, 150, 0) KM150
FROM A6_LRS;

-- 2D

SELECT SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) CLIPPED
FROM A6_LRS;

-- 2E

SELECT SDO_LRS.GET_NEXT_SHAPE_PT(A6_LRS.GEOM, MC.GEOM) WJAZD_NA_A6
FROM A6_LRS, MAJOR_CITIES MC
WHERE MC.CITY_NAME = 'Slupsk';

-- 2F

SELECT SDO_GEOM.SDO_LENGTH(SDO_LRS.OFFSET_GEOM_SEGMENT(A6_LRS.GEOM, MD.DIMINFO, 50, 200, 50,'unit=m arc_tolerance=1'), 1, 'unit=km') KOSZT
FROM A6_LRS, USER_SDO_GEOM_METADATA MD
WHERE MD.TABLE_NAME = 'A6_LRS' 
AND MD.COLUMN_NAME = 'GEOM';